USE [master]
GO

/****** Object:  Database [Teste]    Script Date: 10/04/2021 15:34:56 ******/
CREATE DATABASE [Teste]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Teste', FILENAME = N'C:\Users\stephan\Teste.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Teste_log', FILENAME = N'C:\Users\stephan\Teste_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Teste].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Teste] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Teste] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Teste] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Teste] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Teste] SET ARITHABORT OFF 
GO

ALTER DATABASE [Teste] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Teste] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Teste] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Teste] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Teste] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Teste] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Teste] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Teste] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Teste] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Teste] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Teste] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Teste] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Teste] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Teste] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Teste] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Teste] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Teste] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Teste] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Teste] SET  MULTI_USER 
GO

ALTER DATABASE [Teste] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Teste] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Teste] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Teste] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Teste] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Teste] SET QUERY_STORE = OFF
GO

USE [Teste]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Teste] SET  READ_WRITE 
GO

