USE [master]
GO

/****** Object:  Database [AulaCrud]    Script Date: 17/05/2021 20:56:50 ******/
CREATE DATABASE [AulaCrud]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AulaCrud', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AulaCrud.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AulaCrud_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AulaCrud_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AulaCrud].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AulaCrud] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AulaCrud] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AulaCrud] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AulaCrud] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AulaCrud] SET ARITHABORT OFF 
GO

ALTER DATABASE [AulaCrud] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AulaCrud] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AulaCrud] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AulaCrud] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AulaCrud] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AulaCrud] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AulaCrud] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AulaCrud] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AulaCrud] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AulaCrud] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AulaCrud] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AulaCrud] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AulaCrud] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AulaCrud] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AulaCrud] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AulaCrud] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AulaCrud] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AulaCrud] SET RECOVERY FULL 
GO

ALTER DATABASE [AulaCrud] SET  MULTI_USER 
GO

ALTER DATABASE [AulaCrud] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AulaCrud] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AulaCrud] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AulaCrud] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AulaCrud] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AulaCrud] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AulaCrud] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AulaCrud] SET  READ_WRITE 
GO

